travis:
  secure:
    BINSTAR_TOKEN: bEcvp8qS0BKGmgVdmrECQ0GQ+AJukMBEtG87nbi7fUPmMUrXBpRRcJ3Ou2Y8IH13jd6UT1enKUz17Fr/3vp9Qh08p7cF/wjA9Id0rpJuPCIvOXAPwAiKE4T8Sk2xEh3TXIqG28jjIgnyyUGOqDq4YT8Rj+sog/cKJrWQVorWGoVAztgVCtulIP87fobEyItOmc+SzhOl4cGh5asYNw/Rvr42NxFNELrUT/b0i8Dsn2u0gVDXnKuZALsFN9mOBwFmWyFwAVa1QdO3nBWXmRvHwOFjqadHbXb5qlkjdVZlBMLK5UkWLg60gAqVBFMV+E5lC2FKeg9oj7vWQA48uULggEuT9jq7DHPyMLK/lJl+MqOZK35Jz5qxsM8M9kzA67TMy1L3327bNjB8/LM5rOMOTdD3YmtGTcRyKTvAWRI8bfwyn+ktcqf7I46bN47+LNcIpjjunXo9PVzNYNmtCg3ccnF8eUj7GAUtKIAIM6BNIN4UqR9qFmU50iR+DB2di+SEKH9WWxTZ+UdJ3OjZvN71MDR0cD0E2qiYL2qMf0HO3WJAyAwLmw56TQZE3ki1LXMVCgaLnDHhDp0SzaOIUy+sqWjPuW0Vh8rYAKsk4xP4lfymzzmZNrC9kyfgvPUwx30Ayt8t+gJDXb9rMqdgaxQo1ntilYqhgXPbo9UFa6vn7Fg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
